[features]
seeds = false
skip-lint = false
[programs.localnet]
formigo_program = "EbrRxe4fwd3qoSxEa677TdRTaBV613XHv8RN7EHJnSxE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/exidz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
